apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ci-cd-app-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: ci-cd-app
  namespaceSelector:
    matchNames:
      - gitops
  endpoints:
    - port: http
      path: /metrics
      interval: 15s